// Fixed bot team pools by difficulty. The bot ONLY picks teams from the pool that
// matches the match difficulty — never a random club. Pools are disjoint (a team
// never appears in two levels). `name` is the display reference; `q` is the search
// term used to resolve it to a real club id in the database (full names for
// abbreviations so resolution is unambiguous).
export interface PoolTeam { name: string; q: string }

export const BOT_POOLS: Record<'easy' | 'medium' | 'hard', PoolTeam[]> = {
  // EASY — teams everyone knows.
  easy: [
    { name: 'Real Madrid', q: 'Real Madrid' },
    { name: 'Barcelona', q: 'FC Barcelona' },
    { name: 'Manchester United', q: 'Man Utd' },
    { name: 'Manchester City', q: 'Man City' },
    { name: 'Liverpool', q: 'Liverpool' },
    { name: 'Arsenal', q: 'Arsenal' },
    { name: 'Chelsea', q: 'Chelsea' },
    { name: 'Tottenham', q: 'Tottenham' },
    { name: 'Bayern Munich', q: 'Bayern Munchen' },
    { name: 'Borussia Dortmund', q: 'Dortmund' },
    { name: 'PSG', q: 'PSG' },
    { name: 'Juventus', q: 'Juventus' },
    { name: 'Inter', q: 'Inter' },
    { name: 'Milan', q: 'AC Milan' },
    { name: 'Napoli', q: 'Napoli' },
    { name: 'Atletico Madrid', q: 'Atletico de Madrid' },
    { name: 'Ajax', q: 'Ajax' },
    { name: 'Benfica', q: 'Benfica' },
    { name: 'Porto', q: 'FC Porto' },
    { name: 'Galatasaray', q: 'Galatasaray' },
    { name: 'Fenerbahce', q: 'Fenerbahce' },
    { name: 'Besiktas', q: 'Besiktas' },
  ],
  // MEDIUM — needs a bit of football knowledge.
  medium: [
    { name: 'Sevilla', q: 'Sevilla' },
    { name: 'Villarreal', q: 'Villarreal' },
    { name: 'Real Sociedad', q: 'Real Sociedad' },
    { name: 'Real Betis', q: 'Real Betis' },
    { name: 'Valencia', q: 'Valencia' },
    { name: 'Lazio', q: 'Lazio' },
    { name: 'Roma', q: 'AS Roma' },
    { name: 'Atalanta', q: 'Atalanta' },
    { name: 'Fiorentina', q: 'Fiorentina' },
    { name: 'Marseille', q: 'Olympique de Marseille' },
    { name: 'Lyon', q: 'Lyon' },
    { name: 'Monaco', q: 'AS Monaco' },
    { name: 'Lille', q: 'Lille' },
    { name: 'Sporting CP', q: 'Sporting CP' },
    { name: 'Braga', q: 'SC Braga' },
    { name: 'PSV', q: 'PSV' },
    { name: 'Feyenoord', q: 'Feyenoord' },
    { name: 'AZ Alkmaar', q: 'AZ Alkmaar' },
    { name: 'Celtic', q: 'Celtic' },
    { name: 'Rangers', q: 'Rangers' },
    { name: 'Trabzonspor', q: 'Trabzonspor' },
    { name: 'Basaksehir', q: 'Istanbul Basaksehir' },
    { name: 'Konyaspor', q: 'Konyaspor' },
    { name: 'Anderlecht', q: 'Anderlecht' },
    { name: 'Club Brugge', q: 'Club Brugge' },
    { name: 'Dinamo Zagreb', q: 'Dinamo Zagreb' },
    { name: 'Shakhtar Donetsk', q: 'Shakhtar Donetsk' },
    { name: 'Salzburg', q: 'Salzburg' },
  ],
  // HARD — for serious football fans.
  hard: [
    { name: 'Bodo/Glimt', q: 'Bodo Glimt' },
    { name: 'Molde', q: 'Molde' },
    { name: 'Rosenborg', q: 'Rosenborg' },
    { name: 'HJK Helsinki', q: 'HJK Helsinki' },
    { name: 'Midtjylland', q: 'Midtjylland' },
    { name: 'Nordsjaelland', q: 'Nordsjaelland' },
    { name: 'Brondby', q: 'Brondby' },
    { name: 'AIK', q: 'AIK' },
    { name: 'Malmo', q: 'Malmo FF' },
    { name: 'Djurgarden', q: 'Djurgardens' },
    { name: 'Gent', q: 'KAA Gent' },
    { name: 'Genk', q: 'Genk' },
    { name: 'Union Saint-Gilloise', q: 'Union Saint-Gilloise' },
    { name: 'Slovan Bratislava', q: 'Slovan Bratislava' },
    { name: 'Sparta Prague', q: 'Sparta Prague' },
    { name: 'Viktoria Plzen', q: 'Viktoria Plzen' },
    { name: 'Legia Warsaw', q: 'Legia Warszawa' },
    { name: 'Lech Poznan', q: 'Lech Poznan' },
    { name: 'Ferencvaros', q: 'Ferencvaros' },
    { name: 'Ludogorets', q: 'Ludogorets' },
    { name: 'Sheriff Tiraspol', q: 'Sheriff' },
    { name: 'Qarabag', q: 'Qarabag' },
    { name: 'Astana', q: 'Astana' },
    { name: 'Partizan', q: 'Partizan' },
    { name: 'Crvena Zvezda', q: 'Red Star' },
    { name: 'Maribor', q: 'NK Maribor' },
    { name: 'Olimpija Ljubljana', q: 'Olimpija Ljubljana' },
    { name: 'Zrinjski Mostar', q: 'Zrinjski' },
    { name: 'Dinamo Tbilisi', q: 'Dinamo Tbilisi' },
    { name: 'Maccabi Haifa', q: 'Maccabi Haifa' },
  ],
};
