CREATE TABLE IF NOT EXISTS bot_match_profiles (
  match_id UUID PRIMARY KEY,
  room_code TEXT NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  bot_id TEXT NOT NULL,
  bot_name TEXT NOT NULL,
  algorithm_version TEXT NOT NULL,
  balance_version TEXT NOT NULL,
  rollout_variant TEXT NOT NULL,
  segment TEXT,
  game_mode TEXT NOT NULL,
  player_trophies INT NOT NULL,
  player_skill_mean DOUBLE PRECISION,
  player_skill_uncertainty DOUBLE PRECISION,
  player_matches_played INT,
  target_win_probability DOUBLE PRECISION,
  estimated_player_win_probability DOUBLE PRECISION,
  target_bot_skill DOUBLE PRECISION,
  target_skill_mean DOUBLE PRECISION,
  selected_bot_skill DOUBLE PRECISION NOT NULL,
  selected_bot_skill_mean DOUBLE PRECISION NOT NULL,
  bot_difficulty TEXT NOT NULL,
  bot_archetype TEXT NOT NULL,
  knowledge_depth DOUBLE PRECISION NOT NULL,
  recall_consistency DOUBLE PRECISION NOT NULL,
  reaction_speed DOUBLE PRECISION NOT NULL,
  input_speed DOUBLE PRECISION NOT NULL,
  pressure_handling DOUBLE PRECISION NOT NULL,
  answer_confidence DOUBLE PRECISION NOT NULL,
  question_depth_tolerance DOUBLE PRECISION NOT NULL,
  mistake_probability DOUBLE PRECISION NOT NULL,
  timeout_probability DOUBLE PRECISION NOT NULL,
  participation_rate DOUBLE PRECISION NOT NULL,
  response_median_ms INT NOT NULL,
  response_variance_ms INT NOT NULL,
  frustration_risk DOUBLE PRECISION,
  dominance_score DOUBLE PRECISION,
  intentional_loss_risk DOUBLE PRECISION,
  progression_adjustment_mmr INT,
  form_adjustment_mmr INT,
  recovery_adjustment_mmr INT,
  dominance_adjustment_mmr INT,
  pressure_adjustment_mmr INT,
  smoothing_adjustment_mmr INT,
  liveops_adjustment_mmr INT,
  queue_duration_ms INT NOT NULL,
  queue_health JSONB NOT NULL DEFAULT '{}',
  pressure_profile JSONB NOT NULL DEFAULT '{}',
  economy_state TEXT,
  profile_snapshot JSONB NOT NULL DEFAULT '{}',
  director_snapshot JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bot_match_profiles_user_recent ON bot_match_profiles(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bot_match_profiles_segment_recent ON bot_match_profiles(segment, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bot_match_profiles_bot_recent ON bot_match_profiles(bot_id, created_at DESC);

CREATE TABLE IF NOT EXISTS bot_round_outcomes (
  id BIGSERIAL PRIMARY KEY,
  match_id UUID NOT NULL,
  room_code TEXT NOT NULL,
  round_number INT NOT NULL,
  game_mode TEXT NOT NULL,
  question_key TEXT,
  question_difficulty DOUBLE PRECISION,
  answer_popularity DOUBLE PRECISION,
  valid_answer_count INT,
  bot_id TEXT,
  bot_skill DOUBLE PRECISION,
  bot_skill_mean DOUBLE PRECISION,
  cognitive_state TEXT,
  knows_answer BOOLEAN,
  will_answer BOOLEAN,
  should_mistake BOOLEAN,
  should_timeout BOOLEAN,
  reaction_delay_ms INT,
  knows_probability DOUBLE PRECISION,
  wrong_association_probability DOUBLE PRECISION,
  timeout_probability DOUBLE PRECISION,
  participation_probability DOUBLE PRECISION,
  answered_by_bot BOOLEAN NOT NULL DEFAULT FALSE,
  answered_by_human BOOLEAN NOT NULL DEFAULT FALSE,
  correct BOOLEAN NOT NULL DEFAULT FALSE,
  reason TEXT NOT NULL,
  response_time_ms INT,
  score JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(match_id, round_number)
);

CREATE INDEX IF NOT EXISTS idx_bot_round_outcomes_match ON bot_round_outcomes(match_id, round_number);
CREATE INDEX IF NOT EXISTS idx_bot_round_outcomes_question ON bot_round_outcomes(question_key, created_at DESC);
