# Sonradan eklenen UI2 anahtarları — her anahtar 21 dil. apply_extra.py ile i18n.ts (tr/en) + json'lara işlenir.
EXTRA = {
 'ui2.emptySlot': {'tr': 'Boş yuva', 'en': 'Empty slot', 'de': 'Leerer Platz', 'fr': 'Emplacement vide', 'es': 'Hueco vacío', 'it': 'Slot vuoto', 'pt': 'Espaço vazio', 'nl': 'Leeg vak', 'no': 'Tom plass', 'fi': 'Tyhjä paikka', 'ru': 'Пустая ячейка', 'zh-Hans': '空槽位', 'zh-Hant': '空欄位', 'ja': '空きスロット', 'ko': '빈 슬롯', 'ar': 'خانة فارغة', 'fa': 'جایگاه خالی', 'ms': 'Slot kosong', 'id': 'Slot kosong', 'th': 'ช่องว่าง', 'vi': 'Ô trống'},
 'ui2.questsLabel': {'tr': 'Görevler', 'en': 'Quests', 'de': 'Aufgaben', 'fr': 'Missions', 'es': 'Misiones', 'it': 'Missioni', 'pt': 'Missões', 'nl': 'Opdrachten', 'no': 'Oppdrag', 'fi': 'Tehtävät', 'ru': 'Задания', 'zh-Hans': '任务', 'zh-Hant': '任務', 'ja': 'クエスト', 'ko': '퀘스트', 'ar': 'المهام', 'fa': 'مأموریت‌ها', 'ms': 'Misi', 'id': 'Misi', 'th': 'ภารกิจ', 'vi': 'Nhiệm vụ'},
 'ui2.weeklyShop': {'tr': 'HAFTALIK DÜKKÂN', 'en': 'WEEKLY SHOP', 'de': 'WOCHENSHOP', 'fr': 'BOUTIQUE DE LA SEMAINE', 'es': 'TIENDA SEMANAL', 'it': 'NEGOZIO SETTIMANALE', 'pt': 'LOJA SEMANAL', 'nl': 'WEEKWINKEL', 'no': 'UKESBUTIKK', 'fi': 'VIIKKOKAUPPA', 'ru': 'МАГАЗИН НЕДЕЛИ', 'zh-Hans': '每周商店', 'zh-Hant': '每週商店', 'ja': 'ウィークリーショップ', 'ko': '주간 상점', 'ar': 'متجر الأسبوع', 'fa': 'فروشگاه هفتگی', 'ms': 'KEDAI MINGGUAN', 'id': 'TOKO MINGGUAN', 'th': 'ร้านค้าประจำสัปดาห์', 'vi': 'CỬA HÀNG TUẦN'},
 'ui2.weeklyShopSub': {'tr': 'Bu haftaya özel ürünler!', 'en': "This week's exclusive items!", 'de': 'Exklusive Artikel dieser Woche!', 'fr': 'Articles exclusifs de la semaine !', 'es': '¡Artículos exclusivos de esta semana!', 'it': 'Articoli esclusivi della settimana!', 'pt': 'Itens exclusivos desta semana!', 'nl': 'Exclusieve items van deze week!', 'no': 'Ukens eksklusive varer!', 'fi': 'Tämän viikon erikoistuotteet!', 'ru': 'Эксклюзив этой недели!', 'zh-Hans': '本周限定商品！', 'zh-Hant': '本週限定商品！', 'ja': '今週限定アイテム！', 'ko': '이번 주 한정 아이템!', 'ar': 'عناصر حصرية لهذا الأسبوع!', 'fa': 'آیتم\u200cهای ویژه این هفته!', 'ms': 'Item eksklusif minggu ini!', 'id': 'Item eksklusif minggu ini!', 'th': 'ไอเทมพิเศษประจำสัปดาห์นี้!', 'vi': 'Vật phẩm độc quyền tuần này!'},
 'ui2.resetsIn': {'tr': 'Yenilenme: {t}', 'en': 'Resets in {t}', 'de': 'Neu in {t}', 'fr': 'Renouvelé dans {t}', 'es': 'Se renueva en {t}', 'it': 'Si rinnova tra {t}', 'pt': 'Renova em {t}', 'nl': 'Vernieuwt over {t}', 'no': 'Fornyes om {t}', 'fi': 'Uusiutuu: {t}', 'ru': 'Обновится через {t}', 'zh-Hans': '{t}后刷新', 'zh-Hant': '{t}後刷新', 'ja': 'あと{t}で更新', 'ko': '{t} 후 갱신', 'ar': 'يتجدد خلال {t}', 'fa': 'تازه\u200cسازی در {t}', 'ms': 'Diperbaharui dalam {t}', 'id': 'Diperbarui dalam {t}', 'th': 'รีเซ็ตใน {t}', 'vi': 'Làm mới sau {t}'},
 'ui2.dh': {'tr': '{d}g {h}s', 'en': '{d}d {h}h', 'de': '{d}T {h}Std', 'fr': '{d}j {h}h', 'es': '{d}d {h}h', 'it': '{d}g {h}h', 'pt': '{d}d {h}h', 'nl': '{d}d {h}u', 'no': '{d}d {h}t', 'fi': '{d}pv {h}t', 'ru': '{d}д {h}ч', 'zh-Hans': '{d}天{h}小时', 'zh-Hant': '{d}天{h}小時', 'ja': '{d}日{h}時間', 'ko': '{d}일 {h}시간', 'ar': '{d}ي {h}س', 'fa': '{d}روز {h}ساعت', 'ms': '{d}h {h}j', 'id': '{d}h {h}j', 'th': '{d}ว {h}ชม', 'vi': '{d}ng {h}g'},
 'ui2.hm': {'tr': '{h}s {m}d', 'en': '{h}h {m}m', 'de': '{h}Std {m}Min', 'fr': '{h}h {m}min', 'es': '{h}h {m}min', 'it': '{h}h {m}min', 'pt': '{h}h {m}min', 'nl': '{h}u {m}m', 'no': '{h}t {m}m', 'fi': '{h}t {m}min', 'ru': '{h}ч {m}м', 'zh-Hans': '{h}小时{m}分', 'zh-Hant': '{h}小時{m}分', 'ja': '{h}時間{m}分', 'ko': '{h}시간 {m}분', 'ar': '{h}س {m}د', 'fa': '{h}ساعت {m}دقیقه', 'ms': '{h}j {m}m', 'id': '{h}j {m}m', 'th': '{h}ชม {m}น', 'vi': '{h}g {m}p'},
 'ui2.vault': {'tr': 'KASA', 'en': 'VAULT', 'de': 'TRESOR', 'fr': 'COFFRE', 'es': 'BÓVEDA', 'it': 'CAVEAU', 'pt': 'COFRE', 'nl': 'KLUIS', 'no': 'HVELV', 'fi': 'HOLVI', 'ru': 'СЕЙФ', 'zh-Hans': '宝库', 'zh-Hant': '寶庫', 'ja': '金庫', 'ko': '금고', 'ar': 'الخزنة', 'fa': 'گاوصندوق', 'ms': 'PETI', 'id': 'BRANKAS', 'th': 'ห้องนิรภัย', 'vi': 'KHO BÁU'},
 'ui2.matchPowersSub': {'tr': 'Maçta fark yarat!', 'en': 'Turn the match around!', 'de': 'Dreh das Spiel!', 'fr': 'Renverse le match !', 'es': '¡Cambia el partido!', 'it': 'Ribalta la partita!', 'pt': 'Vire o jogo!', 'nl': 'Draai de wedstrijd om!', 'no': 'Snu kampen!', 'fi': 'Käännä ottelu!', 'ru': 'Переломи матч!', 'zh-Hans': '扭转比赛！', 'zh-Hant': '扭轉比賽！', 'ja': '試合をひっくり返せ！', 'ko': '경기를 뒤집어라!', 'ar': 'اقلب المباراة!', 'fa': 'بازی را برگردان!', 'ms': 'Ubah perlawanan!', 'id': 'Balikkan pertandingan!', 'th': 'พลิกเกม!', 'vi': 'Lật ngược trận đấu!'},
}
