#!/usr/bin/env python3
"""legends workflow JSON -> deploy/legends.sql

Reads the verified legends dataset (research workflow output), resolves club
names against the LOCAL prod-copy staging (crossover_dev.tm_clubs), and writes
an idempotent legends.sql that:
  - creates persistent source tables legends_players / legends_spells
    (so tm-swap.sql can re-merge after any future rebuild),
  - upserts the players (real TM id when found, else 990000000+ synthetic),
  - creates club rows for clubs that don't exist yet (980000000+ synthetic),
  - merges into live players / player_clubs, skipping name_norm duplicates.

Usage: python3 gen-legends-sql.py <results.json>
Prints unresolved-club and skipped-player reports to stderr; SQL to legends.sql.
"""
import json, subprocess, sys, unicodedata, pathlib

SRC = sys.argv[1] if len(sys.argv) > 1 else 'legends-results.json'
OUT = pathlib.Path(__file__).parent / 'legends.sql'

TR = str.maketrans('çğıöşüÇĞİÖŞÜ', 'cgiosuCGIOSU')
def norm(s: str) -> str:
    s = s.translate(TR)
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return ' '.join(s.lower().split())

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

def psql(sql: str) -> list[list[str]]:
    r = subprocess.run(['psql', 'crossover_dev', '-t', '-A', '-F', '\t', '-c', sql],
                       capture_output=True, text=True, check=True)
    return [line.split('\t') for line in r.stdout.strip().split('\n') if line]

# name_norm -> id for every existing club (staging mirror of prod)
clubs = {r[1]: int(r[0]) for r in psql('SELECT id, name_norm FROM tm_clubs')}
# common-name aliases where our DB name differs from the colloquial one
ALIAS = {
    'inter': 'inter milan', 'inter milan': 'inter', 'ac milan': 'milan',
    'fc barcelona': 'barcelona', 'juventus fc': 'juventus',
    'sporting lisbon': 'sporting cp', 'porto': 'fc porto',
    'psg': 'paris saint-germain', 'fenerbahce sk': 'fenerbahce',
    'newells old boys': 'newells old boys club',
}

data = json.load(open(SRC))
players = data if isinstance(data, list) else data.get('players', [])

existing = {r[0] for r in psql('SELECT name_norm FROM tm_players')}

def resolve_club(name: str):
    n = norm(name)
    if n in clubs: return clubs[n], None
    if n in ALIAS and ALIAS[n] in clubs: return clubs[ALIAS[n]], None
    # single fuzzy pass via trigram on the DB side
    rows = psql(f"SELECT id, name_norm, similarity({q(n)}, name_norm) s FROM tm_clubs "
                f"WHERE similarity({q(n)}, name_norm) > 0.55 ORDER BY s DESC LIMIT 1")
    if rows: return int(rows[0][0]), rows[0][1]
    return None, None

synth_club = 980000000
synth_player = 990000000
new_clubs, sql_players, sql_spells, skipped = {}, [], [], []

for i, p in enumerate(players):
    name = p['name'].strip()
    nn = norm(name)
    if nn in existing:
        skipped.append(f"SKIP (already in DB): {name}")
        continue
    pid = p.get('tmId') or (synth_player + i)
    by = p.get('birthYear')
    nat = p.get('nationality') or ''
    img = 'NULL'
    sql_players.append(f"({pid}, {q(name)}, {q(nn)}, {by if by else 'NULL'}, {q(nat)})")
    for sp in p.get('spells', []):
        cid, fuzzy = resolve_club(sp['club'])
        if cid is None:
            key = norm(sp['club'])
            if key not in new_clubs:
                synth_club += 1
                new_clubs[key] = (synth_club, sp['club'])
            cid = new_clubs[key][0]
        elif fuzzy:
            print(f"  fuzzy: {sp['club']!r} -> {fuzzy!r} (id {cid}) [{name}]", file=sys.stderr)
        f, t = sp.get('from'), sp.get('to')
        sql_spells.append(f"({pid}, {cid}, {f if f else 'NULL'}, {t if t else 'NULL'})")

lines = ["-- GENERATED by gen-legends-sql.py — curated legends dataset (verified via",
         "-- two-source research; TM scraping is walled, see transfermarkt-rebuild memory).",
         "BEGIN;",
         """
CREATE TABLE IF NOT EXISTS legends_players (
  id bigint PRIMARY KEY, name text NOT NULL, name_norm text NOT NULL,
  birth_year int, nationality text
);
CREATE TABLE IF NOT EXISTS legends_clubs (
  id bigint PRIMARY KEY, name text NOT NULL, name_norm text NOT NULL, country text
);
CREATE TABLE IF NOT EXISTS legends_spells (
  player_id bigint NOT NULL, club_id bigint NOT NULL, start_year int, end_year int,
  PRIMARY KEY (player_id, club_id, start_year)
);
TRUNCATE legends_players, legends_clubs, legends_spells;"""]

if sql_players:
    lines.append("INSERT INTO legends_players(id,name,name_norm,birth_year,nationality) VALUES\n  "
                 + ",\n  ".join(sql_players) + ";")
for key, (cid, cname) in new_clubs.items():
    lines.append(f"INSERT INTO legends_clubs(id,name,name_norm,country) VALUES ({cid}, {q(cname)}, {q(key)}, 'Türkiye');")
if sql_spells:
    lines.append("INSERT INTO legends_spells(player_id,club_id,start_year,end_year) VALUES\n  "
                 + ",\n  ".join(sorted(set(sql_spells))) + ";")

lines.append("""
-- ---- merge into the live tables (idempotent, safe to re-run) ----
INSERT INTO clubs (id, name, name_norm, country)
SELECT lc.id, lc.name, lc.name_norm, lc.country FROM legends_clubs lc
WHERE NOT EXISTS (SELECT 1 FROM clubs c WHERE c.id = lc.id OR c.name_norm = lc.name_norm);

INSERT INTO players (id, name, name_norm, birth_year, nationality)
SELECT lp.id, lp.name, lp.name_norm, lp.birth_year, lp.nationality FROM legends_players lp
WHERE NOT EXISTS (SELECT 1 FROM players p WHERE p.id = lp.id OR p.name_norm = lp.name_norm);

INSERT INTO player_clubs (player_id, club_id, start_year, end_year)
SELECT ls.player_id,
       COALESCE((SELECT c2.id FROM clubs c2 JOIN legends_clubs lc2 ON lc2.id = ls.club_id
                  WHERE c2.name_norm = lc2.name_norm LIMIT 1), ls.club_id),
       ls.start_year, ls.end_year
  FROM legends_spells ls
 WHERE EXISTS (SELECT 1 FROM players p WHERE p.id = ls.player_id)
   AND NOT EXISTS (SELECT 1 FROM player_clubs pc
                    WHERE pc.player_id = ls.player_id AND pc.club_id = ls.club_id
                      AND pc.start_year IS NOT DISTINCT FROM ls.start_year);

UPDATE clubs SET popularity = sub.n
FROM (SELECT club_id, count(*) AS n FROM player_clubs GROUP BY club_id) sub
WHERE clubs.id = sub.club_id;

COMMIT;

-- Smoke: Sergen Yalçın must resolve with a Beşiktaş AND Trabzonspor membership.
SELECT p.name, c.name AS club, pc.start_year, pc.end_year
  FROM players p JOIN player_clubs pc ON pc.player_id = p.id JOIN clubs c ON c.id = pc.club_id
 WHERE p.name_norm = 'sergen yalcin' ORDER BY pc.start_year;""")

OUT.write_text("\n".join(lines) + "\n", encoding='utf-8')
print(f"\n{OUT} yazıldı: {len(sql_players)} oyuncu, {len(sql_spells)} dönem, {len(new_clubs)} yeni kulüp", file=sys.stderr)
for s in skipped: print(s, file=sys.stderr)
