-- GENERATED by gen-legends-sql.py — curated legends dataset (verified via
-- two-source research; TM scraping is walled, see transfermarkt-rebuild memory).
BEGIN;

CREATE TABLE IF NOT EXISTS legends_players (
  id bigint PRIMARY KEY, name text NOT NULL, name_norm text NOT NULL,
  birth_year int, nationality text
);
CREATE TABLE IF NOT EXISTS legends_clubs (
  id bigint PRIMARY KEY, name text NOT NULL, name_norm text NOT NULL, country text
);
CREATE TABLE IF NOT EXISTS legends_spells (
  player_id bigint NOT NULL, club_id bigint NOT NULL, start_year int, end_year int
);
CREATE UNIQUE INDEX IF NOT EXISTS legends_spells_uq
  ON legends_spells (player_id, club_id, COALESCE(start_year, -1));
TRUNCATE legends_players, legends_clubs, legends_spells;
INSERT INTO legends_players(id,name,name_norm,birth_year,nationality) VALUES
  (6904, 'Sergen Yalçın', 'sergen yalcin', 1972, 'Türkiye'),
  (6869, 'Tayfur Havutçu', 'tayfur havutcu', 1970, 'Türkiye'),
  (4752, 'Oktay Derelioğlu', 'oktay derelioglu', 1975, 'Türkiye'),
  (6875, 'İlhan Mansız', 'ilhan mansiz', 1975, 'Türkiye'),
  (8050, 'Hakan Ünsal', 'hakan unsal', 1973, 'Türkiye'),
  (3377, 'Arif Erdem', 'arif erdem', 1972, 'Türkiye'),
  (3380, 'Bülent Korkmaz', 'bulent korkmaz', 1968, 'Türkiye'),
  (3381, 'Ümit Davala', 'umit davala', 1973, 'Türkiye'),
  (7939, 'Gheorghe Hagi', 'gheorghe hagi', 1965, 'Romania'),
  (3129, 'Gheorghe Popescu', 'gheorghe popescu', 1967, 'Romania'),
  (5855, 'Cláudio Taffarel', 'claudio taffarel', 1966, 'Brazil'),
  (9536, 'Adrian Ilie', 'adrian ilie', 1974, 'Romania'),
  (5333, 'Pascal Nouma', 'pascal nouma', 1972, 'France'),
  (92287, 'Daniel Amokachi', 'daniel amokachi', 1972, 'Nigeria'),
  (17126, 'Mehmet Özdilek', 'mehmet ozdilek', 1966, 'Türkiye'),
  (92275, 'Recep Çetin', 'recep cetin', 1965, 'Türkiye'),
  (92239, 'Feyyaz Uçar', 'feyyaz ucar', 1963, 'Türkiye'),
  (92221, 'Oğuz Çetin', 'oguz cetin', 1963, 'Türkiye'),
  (92222, 'Rıdvan Dilmen', 'ridvan dilmen', 1962, 'Türkiye'),
  (92225, 'Aykut Kocaman', 'aykut kocaman', 1965, 'Türkiye'),
  (6867, 'Elvir Bolić', 'elvir bolic', 1971, 'Bosnia-Herzegovina'),
  (6900, 'Elvir Baljić', 'elvir baljic', 1974, 'Bosnia-Herzegovina'),
  (3708, 'Jay-Jay Okocha', 'jay-jay okocha', 1973, 'Nigeria'),
  (4147, 'Ariel Ortega', 'ariel ortega', 1974, 'Argentina'),
  (3504, 'Alpay Özalan', 'alpay ozalan', 1973, 'Türkiye'),
  (90976, 'Tanju Çolak', 'tanju colak', 1963, 'Türkiye'),
  (92276, 'Ali Gültiken', 'ali gultiken', 1965, 'Türkiye'),
  (84880, 'Hami Mandıralı', 'hami mandirali', 1968, 'Türkiye'),
  (115016, 'Ünal Karaman', 'unal karaman', 1966, 'Türkiye'),
  (7236, 'Abdullah Ercan', 'abdullah ercan', 1971, 'Türkiye'),
  (103796, 'Orhan Çıkırıkçı', 'orhan cikirikci', 1967, 'Türkiye'),
  (92281, 'Metin Tekin', 'metin tekin', 1964, 'Türkiye'),
  (7942, 'Romário', 'romario', 1966, 'Brazil'),
  (7080, 'Washington', 'washington', 1975, 'Brazil'),
  (3111, 'Zinedine Zidane', 'zinedine zidane', 1972, 'France'),
  (5959, 'Gabriel Batistuta', 'gabriel batistuta', 1969, 'Argentina'),
  (4153, 'Roberto Baggio', 'roberto baggio', 1967, 'Italy'),
  (8024, 'Diego Maradona', 'diego maradona', 1960, 'Argentina'),
  (3187, 'Dennis Bergkamp', 'dennis bergkamp', 1969, 'Netherlands'),
  (74471, 'Marco van Basten', 'marco van basten', 1964, 'Netherlands');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000001, '1. FC Nürnberg', '1. fc nurnberg', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000002, 'Akçaabat Sebatspor', 'akcaabat sebatspor', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000003, '1. FC Köln II', '1. fc koln ii', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000004, 'Sportul Studențesc', 'sportul studentesc', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000005, 'Steaua București', 'steaua bucuresti', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000006, 'Dinamo București', 'dinamo bucuresti', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000007, 'Reggiana', 'reggiana', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000008, 'Atlético Mineiro', 'atletico mineiro', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000009, 'Electroputere Craiova', 'electroputere craiova', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000010, 'Germinal Beerschot', 'germinal beerschot', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000011, 'Paris Saint-Germain', 'paris saint-germain', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000012, 'Ranchers Bees', 'ranchers bees', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000013, 'Red Star Belgrade', 'red star belgrade', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000014, 'Eintracht Frankfurt', 'eintracht frankfurt', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000015, 'Incheon United', 'incheon united', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000016, 'Caxias', 'caxias', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000017, 'Grêmio', 'gremio', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000018, 'Ponte Preta', 'ponte preta', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (980000019, 'Paraná Clube', 'parana clube', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (5743, 'Tuğranspor', 'tugranspor', 'Türkiye');
INSERT INTO legends_clubs(id,name,name_norm,country) VALUES (1291, 'Siirt JetPA Spor', 'siirt jetpa spor', 'Türkiye');
INSERT INTO legends_spells(player_id,club_id,start_year,end_year) VALUES
  (103796, 20707, NULL, 1988),
  (103796, 449, 1989, 2002),
  (103796, 825, 1988, 1989),
  (103796, 980000002, 2001, 2002),
  (115016, 1264, 1987, 1990),
  (115016, 449, 1990, 1999),
  (115016, 524, 1984, 1987),
  (115016, 868, 1999, 2000),
  (17126, 114, 1988, 2001),
  (17126, 12452, 1984, 1988),
  (3111, 40, 1992, 1996),
  (3111, 418, 2001, 2006),
  (3111, 506, 1996, 2001),
  (3111, 895, 1989, 1992),
  (3129, 1005, 2001, 2002),
  (3129, 131, 1995, 1997),
  (3129, 141, 1997, 2001),
  (3129, 148, 1994, 1995),
  (3129, 37239, 1982, 1984),
  (3129, 3892, 1990, 1994),
  (3129, 40812, 1985, 1990),
  (3129, 42, 2002, 2003),
  (3129, 980000005, 1988, 1988),
  (3129, 980000006, 2002, 2002),
  (3187, 11, 1995, 2006),
  (3187, 46, 1993, 1995),
  (3187, 610, 1986, 1993),
  (3377, 141, 1991, 2000),
  (3377, 141, 2000, 2005),
  (3377, 5745, 1990, 1991),
  (3377, 681, 2000, 2000),
  (3380, 141, 1987, 2005),
  (3381, 141, 1996, 2001),
  (3381, 141, 2002, 2003),
  (3381, 1783, 1992, 1994),
  (3381, 46, 2002, 2004),
  (3381, 49078, 1994, 1994),
  (3381, 5, 2001, 2002),
  (3381, 845, 1996, 1996),
  (3381, 86, 2003, 2004),
  (3381, 86, 2004, 2006),
  (3381, 924, 1994, 1996),
  (3504, 114, 1993, 1999),
  (3504, 2375, 1992, 1993),
  (3504, 3, 2005, 2008),
  (3504, 36, 1999, 2000),
  (3504, 405, 2000, 2004),
  (3504, 50852, 1991, 1992),
  (3504, 828, 2004, 2005),
  (3504, 980000015, 2004, 2004),
  (3708, 124, 1989, 1990),
  (3708, 3008, 2007, 2008),
  (3708, 328, 1990, 1992),
  (3708, 355, 2002, 2006),
  (3708, 36, 1996, 1998),
  (3708, 965, 2006, 2007),
  (3708, 980000011, 1998, 2002),
  (3708, 980000014, 1992, 1996),
  (4147, 1038, 1998, 1999),
  (4147, 1049, 1997, 1998),
  (4147, 12100, 2011, 2011),
  (4147, 12179, 2008, 2009),
  (4147, 1286, 2004, 2006),
  (4147, 130, 1999, 2000),
  (4147, 209, 1991, 1997),
  (4147, 209, 2000, 2002),
  (4147, 209, 2006, 2012),
  (4147, 36, 2002, 2003),
  (4147, 6062, 2011, 2012),
  (4153, 1025, 1997, 1998),
  (4153, 19, 2000, 2004),
  (4153, 2655, 1982, 1985),
  (4153, 430, 1985, 1990),
  (4153, 46, 1998, 2000),
  (4153, 5, 1995, 1997),
  (4153, 506, 1990, 1995),
  (4752, 114, 1993, 1999),
  (4752, 1291, 1999, 1999),
  (4752, 152, 2003, 2003),
  (4752, 2463, 2005, 2005),
  (4752, 36, 2001, 2003),
  (4752, 449, 1992, 1993),
  (4752, 449, 2000, 2001),
  (4752, 472, 2000, 2000),
  (4752, 524, 1999, 2000),
  (4752, 6646, 1990, 1992),
  (4752, 6646, 2007, 2008),
  (4752, 845, 2006, 2006),
  (4752, 8841, 2004, 2005),
  (4752, 924, 2006, 2007),
  (4752, 980000001, 2003, 2004),
  (4752, 980000002, 2004, 2004),
  (4752, 9935, 2007, 2007),
  (5333, 1082, 1992, 1993),
  (5333, 114, 2000, 2001),
  (5333, 114, 2002, 2003),
  (5333, 1162, 1993, 1994),
  (5333, 1241, 2004, 2005),
  (5333, 244, 2001, 2002),
  (5333, 5381, 2003, 2004),
  (5333, 667, 1996, 1998),
  (5333, 826, 1998, 2000),
  (5333, 980000011, 1989, 1992),
  (5333, 980000011, 1994, 1996),
  (5855, 130, 1990, 1993),
  (5855, 130, 2001, 2003),
  (5855, 141, 1998, 2001),
  (5855, 46403, 1985, 1990),
  (5855, 980000007, 1993, 1994),
  (5855, 980000008, 1995, 1998),
  (5959, 12, 2000, 2003),
  (5959, 1286, 1988, 1989),
  (5959, 189, 1990, 1991),
  (5959, 209, 1989, 1990),
  (5959, 430, 1991, 2000),
  (5959, 46, 2003, 2003),
  (5959, 68834, 2003, 2005),
  (6867, 1264, 2005, 2005),
  (6867, 141, 1992, 1993),
  (6867, 144, 2006, 2007),
  (6867, 36, 1995, 2000),
  (6867, 367, 2000, 2003),
  (6867, 524, 1993, 1995),
  (6867, 765, 1988, 1991),
  (6867, 820, 2004, 2004),
  (6867, 924, 2003, 2004),
  (6867, 924, 2005, 2006),
  (6867, 980000013, 1991, 1992),
  (6869, 105, 1992, 1993),
  (6869, 114, 1997, 2006),
  (6869, 120, 1995, 1997),
  (6869, 36, 1993, 1995),
  (6875, 114, 2001, 2004),
  (6875, 12456, 1996, 1997),
  (6875, 152, 1998, 2001),
  (6875, 2318, 1997, 1998),
  (6875, 3958, 2004, 2004),
  (6875, 44, 2005, 2005),
  (6875, 820, 1995, 1996),
  (6875, 868, 2005, 2006),
  (6875, 980000003, 1994, 1995),
  (6900, 141, 2002, 2004),
  (6900, 20, 1995, 1998),
  (6900, 2293, 2005, 2005),
  (6900, 282, 1993, 1995),
  (6900, 36, 1998, 1999),
  (6900, 36, 2000, 2001),
  (6900, 367, 2001, 2002),
  (6900, 418, 1999, 2002),
  (6900, 868, 2005, 2006),
  (6900, 924, 2006, 2008),
  (6904, 114, 1991, 1997),
  (6904, 114, 2002, 2006),
  (6904, 141, 1999, 2000),
  (6904, 141, 2001, 2002),
  (6904, 36, 1999, 1999),
  (6904, 449, 2000, 2001),
  (6904, 1291, 1999, 2002),
  (6904, 5743, 2006, 2007),
  (6904, 825, 2007, 2008),
  (6904, 924, 1997, 1999),
  (7080, 2462, 2008, 2008),
  (7080, 2462, 2010, 2011),
  (7080, 26491, 2004, 2004),
  (7080, 36, 2002, 2003),
  (7080, 3734, 2005, 2005),
  (7080, 46403, 1997, 1997),
  (7080, 585, 2009, 2010),
  (7080, 828, 2006, 2007),
  (7080, 980000016, 1993, 1999),
  (7080, 980000017, 1997, 1997),
  (7080, 980000018, 1998, 1998),
  (7080, 980000018, 2000, 2002),
  (7080, 980000019, 1999, 2000),
  (7236, 141, 2003, 2004),
  (7236, 36, 1999, 2003),
  (7236, 449, 1990, 1999),
  (7236, 924, 2004, 2006),
  (74471, 5, 1987, 1995),
  (74471, 610, 1981, 1987),
  (7939, 131, 1994, 1996),
  (7939, 141, 1996, 2001),
  (7939, 19, 1992, 1994),
  (7939, 418, 1990, 1992),
  (7939, 5267, 1982, 1983),
  (7939, 980000004, 1983, 1987),
  (7939, 980000005, 1987, 1990),
  (7942, 1049, 1996, 1997),
  (7942, 1049, 1997, 1998),
  (7942, 131, 1993, 1995),
  (7942, 2462, 2002, 2004),
  (7942, 38337, 2009, 2009),
  (7942, 3892, 1988, 1993),
  (7942, 42814, 2006, 2006),
  (7942, 614, 1995, 1996),
  (7942, 614, 1997, 1997),
  (7942, 614, 1998, 1999),
  (7942, 656, 2003, 2003),
  (7942, 875, 2006, 2006),
  (7942, 978, 1985, 1988),
  (7942, 978, 2000, 2002),
  (7942, 978, 2005, 2006),
  (7942, 978, 2007, 2008),
  (8024, 1030, 1976, 1981),
  (8024, 1286, 1993, 1994),
  (8024, 131, 1982, 1984),
  (8024, 189, 1981, 1982),
  (8024, 189, 1995, 1997),
  (8024, 368, 1992, 1993),
  (8024, 6195, 1984, 1992),
  (8050, 126, 2005, 2006),
  (8050, 141, 1994, 2002),
  (8050, 141, 2002, 2005),
  (8050, 1506, 1993, 1994),
  (8050, 164, 2002, 2002),
  (8050, 7160, 1991, 1993),
  (84880, 33, 1998, 1999),
  (84880, 449, 1984, 1998),
  (84880, 449, 1999, 2002),
  (84880, 868, 2002, 2002),
  (90976, 141, 1987, 1991),
  (90976, 152, 1981, 1987),
  (90976, 36, 1991, 1993),
  (90976, 924, 1993, 1994),
  (92221, 2463, 1981, 1988),
  (92221, 36, 1988, 1996),
  (92221, 6, 1999, 2000),
  (92221, 924, 1996, 1999),
  (92222, 13473, 1977, 1979),
  (92222, 2378, 1979, 1980),
  (92222, 3207, 1980, 1983),
  (92222, 36, 1987, 1995),
  (92222, 82095, 1983, 1987),
  (92225, 2463, 1984, 1988),
  (92225, 36, 1988, 1996),
  (92225, 924, 1996, 2000),
  (92239, 114, 1982, 1994),
  (92239, 2318, 1996, 1997),
  (92239, 36, 1994, 1996),
  (92239, 589, 1995, 1996),
  (92275, 114, 1988, 1998),
  (92275, 3207, 1984, 1988),
  (92275, 449, 1998, 1999),
  (92275, 924, 1999, 2001),
  (92276, 114, 1984, 1995),
  (92276, 3205, 1995, 1996),
  (92281, 114, 1982, 1997),
  (92281, 40181, 1997, 1997),
  (92287, 114, 1996, 1999),
  (92287, 1247, 2002, 2002),
  (92287, 15723, 2005, 2006),
  (92287, 2067, 2000, 2001),
  (92287, 2282, 1990, 1994),
  (92287, 29, 1994, 1996),
  (92287, 980000012, 1989, 1990),
  (9536, 1049, 1998, 2002),
  (9536, 114, 2003, 2004),
  (9536, 141, 1996, 1998),
  (9536, 260, 2004, 2005),
  (9536, 76291, 2002, 2003),
  (9536, 980000005, 1993, 1996),
  (9536, 980000009, 1991, 1993),
  (9536, 980000010, 2005, 2006);

-- ---- merge into the live tables (idempotent, safe to re-run) ----
INSERT INTO clubs (id, name, name_norm, country)
SELECT lc.id, lc.name, lc.name_norm, lc.country FROM legends_clubs lc
WHERE NOT EXISTS (SELECT 1 FROM clubs c WHERE c.id = lc.id OR c.name_norm = lc.name_norm);

UPDATE clubs
   SET name = 'Siirt JetPA Spor',
       name_norm = 'siirt jetpa spor',
       aliases = (
         SELECT array_agg(DISTINCT a)
           FROM unnest(aliases || ARRAY['siirt jetpa', 'siirtjetpa', 'siirt jet pa', 'siirtspor', 'siirtspor 1969 2014']::text[]) AS t(a)
       ),
       logo_url = COALESCE(logo_url, 'https://tmssl.akamaized.net//images/wappen/big/1291.png')
 WHERE id = 1291;

UPDATE clubs
   SET name = 'Tuğranspor',
       name_norm = 'tugranspor',
       aliases = (
         SELECT array_agg(DISTINCT a)
           FROM unnest(aliases || ARRAY['turan spor', 'turanspor', 'sekerspor', 'seker spor', 'etimesgut sekerspor']::text[]) AS t(a)
       ),
       logo_url = COALESCE(logo_url, 'https://tmssl.akamaized.net//images/wappen/big/5743.png')
 WHERE id = 5743;

INSERT INTO players (id, name, name_norm, birth_year, nationality)
SELECT lp.id, lp.name, lp.name_norm, lp.birth_year, lp.nationality FROM legends_players lp
WHERE NOT EXISTS (SELECT 1 FROM players p WHERE p.id = lp.id); -- id-only: namesakes are legitimate

INSERT INTO player_clubs (player_id, club_id, start_year, end_year)
SELECT ls.player_id,
       COALESCE((SELECT c2.id FROM clubs c2 JOIN legends_clubs lc2 ON lc2.id = ls.club_id
                  WHERE c2.name_norm = lc2.name_norm LIMIT 1), ls.club_id),
       ls.start_year, ls.end_year
  FROM legends_spells ls
 WHERE EXISTS (SELECT 1 FROM players p WHERE p.id = ls.player_id)
   AND NOT EXISTS (SELECT 1 FROM player_clubs pc
                    WHERE pc.player_id = ls.player_id AND pc.club_id = ls.club_id
                      AND pc.start_year IS NOT DISTINCT FROM ls.start_year);

UPDATE clubs SET popularity = sub.n
FROM (SELECT club_id, count(*) AS n FROM player_clubs GROUP BY club_id) sub
WHERE clubs.id = sub.club_id;

COMMIT;

-- Smoke: Sergen Yalçın must resolve with Beşiktaş, Trabzonspor, and Siirt JetPA memberships.
SELECT p.name, c.name AS club, pc.start_year, pc.end_year
  FROM players p JOIN player_clubs pc ON pc.player_id = p.id JOIN clubs c ON c.id = pc.club_id
 WHERE p.name_norm = 'sergen yalcin' ORDER BY pc.start_year;
