// Hardcoded nationality list for the country-team game mode picker.
// `value` matches the exact string stored in players.nationality (from Wikidata P27 en labels).
// `displayName` is the Turkish name shown in the UI.
// Sorted alphabetically by Turkish displayName.

export interface Nationality {
  value: string;       // English name matching DB (players.nationality)
  displayName: string; // Turkish name (shown in UI)
  flag: string;        // flag emoji
}

export const NATIONALITIES: Nationality[] = [
  { value: 'United States', displayName: 'ABD', flag: '🇺🇸' },
  { value: 'Albania', displayName: 'Arnavutluk', flag: '🇦🇱' },
  { value: 'Germany', displayName: 'Almanya', flag: '🇩🇪' },
  { value: 'Angola', displayName: 'Angola', flag: '🇦🇴' },
  { value: 'Argentina', displayName: 'Arjantin', flag: '🇦🇷' },
  { value: 'Australia', displayName: 'Avustralya', flag: '🇦🇺' },
  { value: 'Austria', displayName: 'Avusturya', flag: '🇦🇹' },
  { value: 'United-Arab-Emirates', displayName: 'BAE', flag: '🇦🇪' },
  { value: 'Belgium', displayName: 'Belçika', flag: '🇧🇪' },
  { value: 'Bosnia-Herzegovina', displayName: 'Bosna Hersek', flag: '🇧🇦' },
  { value: 'Brazil', displayName: 'Brezilya', flag: '🇧🇷' },
  { value: 'Bulgaria', displayName: 'Bulgaristan', flag: '🇧🇬' },
  { value: 'Algeria', displayName: 'Cezayir', flag: '🇩🇿' },
  { value: 'Czech Republic', displayName: 'Çekya', flag: '🇨🇿' },
  { value: 'China', displayName: 'Çin', flag: '🇨🇳' },
  { value: 'Denmark', displayName: 'Danimarka', flag: '🇩🇰' },
  { value: 'Ecuador', displayName: 'Ekvador', flag: '🇪🇨' },
  { value: 'Morocco', displayName: 'Fas', flag: '🇲🇦' },
  { value: 'Cote d\'Ivoire', displayName: 'Fildişi Sahili', flag: '🇨🇮' },
  { value: 'Finland', displayName: 'Finlandiya', flag: '🇫🇮' },
  { value: 'France', displayName: 'Fransa', flag: '🇫🇷' },
  { value: 'Wales', displayName: 'Galler', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { value: 'Ghana', displayName: 'Gana', flag: '🇬🇭' },
  { value: 'Guinea', displayName: 'Gine', flag: '🇬🇳' },
  { value: 'South Africa', displayName: 'Güney Afrika', flag: '🇿🇦' },
  { value: 'Korea, South', displayName: 'Güney Kore', flag: '🇰🇷' },
  { value: 'Georgia', displayName: 'Gürcistan', flag: '🇬🇪' },
  { value: 'Croatia', displayName: 'Hırvatistan', flag: '🇭🇷' },
  { value: 'Netherlands', displayName: 'Hollanda', flag: '🇳🇱' },
  { value: 'Honduras', displayName: 'Honduras', flag: '🇭🇳' },
  { value: 'Iraq', displayName: 'Irak', flag: '🇮🇶' },
  { value: 'England', displayName: 'İngiltere', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { value: 'Iran', displayName: 'İran', flag: '🇮🇷' },
  { value: 'Ireland', displayName: 'İrlanda', flag: '🇮🇪' },
  { value: 'Scotland', displayName: 'İskoçya', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { value: 'Spain', displayName: 'İspanya', flag: '🇪🇸' },
  { value: 'Israel', displayName: 'İsrail', flag: '🇮🇱' },
  { value: 'Sweden', displayName: 'İsveç', flag: '🇸🇪' },
  { value: 'Switzerland', displayName: 'İsviçre', flag: '🇨🇭' },
  { value: 'Italy', displayName: 'İtalya', flag: '🇮🇹' },
  { value: 'Iceland', displayName: 'İzlanda', flag: '🇮🇸' },
  { value: 'Jamaica', displayName: 'Jamaika', flag: '🇯🇲' },
  { value: 'Japan', displayName: 'Japonya', flag: '🇯🇵' },
  { value: 'Cameroon', displayName: 'Kamerun', flag: '🇨🇲' },
  { value: 'Canada', displayName: 'Kanada', flag: '🇨🇦' },
  { value: 'Montenegro', displayName: 'Karadağ', flag: '🇲🇪' },
  { value: 'Qatar', displayName: 'Katar', flag: '🇶🇦' },
  { value: 'Colombia', displayName: 'Kolombiya', flag: '🇨🇴' },
  { value: 'DR Congo', displayName: 'Kongo', flag: '🇨🇩' },
  { value: 'Kosovo', displayName: 'Kosova', flag: '🇽🇰' },
  { value: 'Costa Rica', displayName: 'Kosta Rika', flag: '🇨🇷' },
  { value: 'Northern Ireland', displayName: 'Kuzey İrlanda', flag: '🇬🇧' },
  { value: 'North Macedonia', displayName: 'Kuzey Makedonya', flag: '🇲🇰' },
  { value: 'Hungary', displayName: 'Macaristan', flag: '🇭🇺' },
  { value: 'Mali', displayName: 'Mali', flag: '🇲🇱' },
  { value: 'Mexico', displayName: 'Meksika', flag: '🇲🇽' },
  { value: 'Egypt', displayName: 'Mısır', flag: '🇪🇬' },
  { value: 'Nigeria', displayName: 'Nijerya', flag: '🇳🇬' },
  { value: 'Norway', displayName: 'Norveç', flag: '🇳🇴' },
  { value: 'Paraguay', displayName: 'Paraguay', flag: '🇵🇾' },
  { value: 'Peru', displayName: 'Peru', flag: '🇵🇪' },
  { value: 'Poland', displayName: 'Polonya', flag: '🇵🇱' },
  { value: 'Portugal', displayName: 'Portekiz', flag: '🇵🇹' },
  { value: 'Romania', displayName: 'Romanya', flag: '🇷🇴' },
  { value: 'Russia', displayName: 'Rusya', flag: '🇷🇺' },
  { value: 'Saudi Arabia', displayName: 'Suudi Arabistan', flag: '🇸🇦' },
  { value: 'Senegal', displayName: 'Senegal', flag: '🇸🇳' },
  { value: 'Serbia', displayName: 'Sırbistan', flag: '🇷🇸' },
  { value: 'Chile', displayName: 'Şili', flag: '🇨🇱' },
  { value: 'Slovakia', displayName: 'Slovakya', flag: '🇸🇰' },
  { value: 'Slovenia', displayName: 'Slovenya', flag: '🇸🇮' },
  { value: 'Tunisia', displayName: 'Tunus', flag: '🇹🇳' },
  { value: 'Türkiye', displayName: 'Türkiye', flag: '🇹🇷' },
  { value: 'Ukraine', displayName: 'Ukrayna', flag: '🇺🇦' },
  { value: 'Uruguay', displayName: 'Uruguay', flag: '🇺🇾' },
  { value: 'Venezuela', displayName: 'Venezuela', flag: '🇻🇪' },
  { value: 'New Zealand', displayName: 'Yeni Zelanda', flag: '🇳🇿' },
  { value: 'Greece', displayName: 'Yunanistan', flag: '🇬🇷' },
  { value: 'Cape Verde', displayName: 'Yeşil Burun Adaları', flag: '🇨🇻' },
].sort((a, b) => a.displayName.localeCompare(b.displayName, 'tr'));
