// Hardcoded nationality list for the country-team game mode picker.
// Turkish display names, flag emojis, and the English DB value (used in protocol).
// Sorted alphabetically by Turkish name.

export interface Nationality {
  value: string;       // English name (sent to server, matches players.nationality)
  displayName: string; // Turkish name (shown in UI)
  flag: string;        // flag emoji
}

export const NATIONALITIES: Nationality[] = [
  { value: 'Germany', displayName: 'Almanya', flag: '🇩🇪' },
  { value: 'United States of America', displayName: 'ABD', flag: '🇺🇸' },
  { value: 'Argentina', displayName: 'Arjantin', flag: '🇦🇷' },
  { value: 'Australia', displayName: 'Avustralya', flag: '🇦🇺' },
  { value: 'Austria', displayName: 'Avusturya', flag: '🇦🇹' },
  { value: 'Belgium', displayName: 'Belcika', flag: '🇧🇪' },
  { value: 'Bolivia', displayName: 'Bolivya', flag: '🇧🇴' },
  { value: 'Brazil', displayName: 'Brezilya', flag: '🇧🇷' },
  { value: 'Bulgaria', displayName: 'Bulgaristan', flag: '🇧🇬' },
  { value: 'Algeria', displayName: 'Cezayir', flag: '🇩🇿' },
  { value: 'Czech Republic', displayName: 'Cekya', flag: '🇨🇿' },
  { value: "People's Republic of China", displayName: 'Cin', flag: '🇨🇳' },
  { value: 'Colombia', displayName: 'Kolombiya', flag: '🇨🇴' },
  { value: 'Croatia', displayName: 'Hirvatistan', flag: '🇭🇷' },
  { value: 'Denmark', displayName: 'Danimarka', flag: '🇩🇰' },
  { value: 'Ecuador', displayName: 'Ekvador', flag: '🇪🇨' },
  { value: 'Finland', displayName: 'Finlandiya', flag: '🇫🇮' },
  { value: 'France', displayName: 'Fransa', flag: '🇫🇷' },
  { value: 'South Africa', displayName: 'Guney Afrika', flag: '🇿🇦' },
  { value: 'South Korea', displayName: 'Guney Kore', flag: '🇰🇷' },
  { value: 'Georgia', displayName: 'Gurcistan', flag: '🇬🇪' },
  { value: 'Netherlands', displayName: 'Hollanda', flag: '🇳🇱' },
  { value: 'England', displayName: 'Ingiltere', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { value: 'Republic of Ireland', displayName: 'Irlanda', flag: '🇮🇪' },
  { value: 'Spain', displayName: 'Ispanya', flag: '🇪🇸' },
  { value: 'Sweden', displayName: 'Isvec', flag: '🇸🇪' },
  { value: 'Switzerland', displayName: 'Isvicre', flag: '🇨🇭' },
  { value: 'Italy', displayName: 'Italya', flag: '🇮🇹' },
  { value: 'Iceland', displayName: 'Izlanda', flag: '🇮🇸' },
  { value: 'Scotland', displayName: 'Iskocya', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { value: 'Jamaica', displayName: 'Jamaika', flag: '🇯🇲' },
  { value: 'Japan', displayName: 'Japonya', flag: '🇯🇵' },
  { value: 'Cameroon', displayName: 'Kamerun', flag: '🇨🇲' },
  { value: 'Canada', displayName: 'Kanada', flag: '🇨🇦' },
  { value: 'Montenegro', displayName: 'Karadag', flag: '🇲🇪' },
  { value: 'Qatar', displayName: 'Katar', flag: '🇶🇦' },
  { value: 'Ivory Coast', displayName: 'Fildisi Sahili', flag: '🇨🇮' },
  { value: 'Costa Rica', displayName: 'Kosta Rika', flag: '🇨🇷' },
  { value: 'Hungary', displayName: 'Macaristan', flag: '🇭🇺' },
  { value: 'North Macedonia', displayName: 'Kuzey Makedonya', flag: '🇲🇰' },
  { value: 'Egypt', displayName: 'Misir', flag: '🇪🇬' },
  { value: 'Morocco', displayName: 'Fas', flag: '🇲🇦' },
  { value: 'Mexico', displayName: 'Meksika', flag: '🇲🇽' },
  { value: 'Nigeria', displayName: 'Nijerya', flag: '🇳🇬' },
  { value: 'Norway', displayName: 'Norvec', flag: '🇳🇴' },
  { value: 'Paraguay', displayName: 'Paraguay', flag: '🇵🇾' },
  { value: 'Peru', displayName: 'Peru', flag: '🇵🇪' },
  { value: 'Poland', displayName: 'Polonya', flag: '🇵🇱' },
  { value: 'Portugal', displayName: 'Portekiz', flag: '🇵🇹' },
  { value: 'Romania', displayName: 'Romanya', flag: '🇷🇴' },
  { value: 'Russia', displayName: 'Rusya', flag: '🇷🇺' },
  { value: 'Senegal', displayName: 'Senegal', flag: '🇸🇳' },
  { value: 'Serbia', displayName: 'Sirbistan', flag: '🇷🇸' },
  { value: 'Slovakia', displayName: 'Slovakya', flag: '🇸🇰' },
  { value: 'Slovenia', displayName: 'Slovenya', flag: '🇸🇮' },
  { value: 'Saudi Arabia', displayName: 'Suudi Arabistan', flag: '🇸🇦' },
  { value: 'Chile', displayName: 'Sili', flag: '🇨🇱' },
  { value: 'Tunisia', displayName: 'Tunus', flag: '🇹🇳' },
  { value: 'Turkey', displayName: 'Turkiye', flag: '🇹🇷' },
  { value: 'Ukraine', displayName: 'Ukrayna', flag: '🇺🇦' },
  { value: 'Uruguay', displayName: 'Uruguay', flag: '🇺🇾' },
  { value: 'Venezuela', displayName: 'Venezuela', flag: '🇻🇪' },
  { value: 'Wales', displayName: 'Galler', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { value: 'Ghana', displayName: 'Gana', flag: '🇬🇭' },
  { value: 'Greece', displayName: 'Yunanistan', flag: '🇬🇷' },
  { value: 'New Zealand', displayName: 'Yeni Zelanda', flag: '🇳🇿' },
  { value: 'Honduras', displayName: 'Honduras', flag: '🇭🇳' },
  { value: 'DR Congo', displayName: 'Kongo', flag: '🇨🇩' },
  { value: 'Mali', displayName: 'Mali', flag: '🇲🇱' },
  { value: 'Guinea', displayName: 'Gine', flag: '🇬🇳' },
  { value: 'Bosnia and Herzegovina', displayName: 'Bosna Hersek', flag: '🇧🇦' },
  { value: 'Albania', displayName: 'Arnavutluk', flag: '🇦🇱' },
  { value: 'Israel', displayName: 'Israil', flag: '🇮🇱' },
  { value: 'Iran', displayName: 'Iran', flag: '🇮🇷' },
  { value: 'Iraq', displayName: 'Irak', flag: '🇮🇶' },
  { value: 'United Arab Emirates', displayName: 'BAE', flag: '🇦🇪' },
  { value: 'Panama', displayName: 'Panama', flag: '🇵🇦' },
  { value: 'Northern Ireland', displayName: 'Kuzey Irlanda', flag: '🇬🇧' },
].sort((a, b) => a.displayName.localeCompare(b.displayName, 'tr'));
