export enum AudioEvent {
  UI_TAP = 'uiTap',
  UI_CONFIRM = 'uiConfirm',
  UI_BACK = 'uiBack',
  UI_CLOSE = 'uiClose',
  UI_OPEN = 'uiOpen',
  UI_TAB_SWITCH = 'uiTabSwitch',
  UI_TOGGLE_ON = 'uiToggleOn',
  UI_TOGGLE_OFF = 'uiToggleOff',
  UI_PURCHASE = 'uiPurchase',
  UI_ERROR = 'uiError',
  COUNTDOWN_3 = 'countdown3',
  COUNTDOWN_2 = 'countdown2',
  COUNTDOWN_1 = 'countdown1',
  MATCH_START = 'matchStart',
  ANSWER_CORRECT = 'answerCorrect',
  ANSWER_WRONG = 'answerWrong',
  OPPONENT_CORRECT = 'opponentCorrect',
  ANSWER_SUBMIT = 'answerSubmit',
  TIMER_WARNING = 'timerWarning',
  TIMER_CRITICAL = 'timerCritical',
  TIMEOUT_IMPACT = 'timeoutImpact',
  ROUND_WIN = 'roundWin',
  ROUND_LOSE = 'roundLose',
  MATCH_WIN = 'matchWin',
  MATCH_LOSE = 'matchLose',
  DRAW = 'draw',
  SCORE_GAIN = 'scoreGain',
  SCORE_LOSE = 'scoreLose',
  MATCHMAKING_FOUND = 'matchmakingFound',
  XP_GAIN = 'xpGain',
  LEVEL_UP = 'levelUp',
  TROPHY_GAIN = 'trophyGain',
  TROPHY_LOSS = 'trophyLoss',
  ARENA_UNLOCK = 'arenaUnlock',
  REWARD_OPEN = 'rewardOpen',
  DIAMOND_GAIN = 'diamondGain',
  ACHIEVEMENT = 'achievement',
  EMOTE_SEND = 'emoteSend',
  EMOTE_RECEIVE = 'emoteReceive',
  NOTIFICATION = 'notification',
  SPECIAL_RONALDO_IMPACT = 'ronaldoImpact',
  SPECIAL_RONALDO_CELEBRATION = 'ronaldoCelebration',
  SPECIAL_CROWD_PUNCH = 'crowdPunch',
}

export enum MusicTrack {
  MAIN_MENU = 'mainMenu',
}

export enum AmbienceTrack {
  STADIUM = 'stadiumAmbience',
}

export enum HapticEvent {
  LIGHT = 'light',
  MEDIUM = 'medium',
  SUCCESS = 'success',
  WARNING = 'warning',
  ERROR = 'error',
  HEAVY = 'heavy',
  SPECIAL = 'special',
}

export enum GameFeedbackEvent {
  UI_TAP = 'UI_TAP',
  UI_CONFIRM = 'UI_CONFIRM',
  UI_BACK = 'UI_BACK',
  UI_CLOSE = 'UI_CLOSE',
  UI_OPEN = 'UI_OPEN',
  UI_TAB_SWITCH = 'UI_TAB_SWITCH',
  UI_TOGGLE_ON = 'UI_TOGGLE_ON',
  UI_TOGGLE_OFF = 'UI_TOGGLE_OFF',
  UI_PURCHASE = 'UI_PURCHASE',
  UI_ERROR = 'UI_ERROR',
  ANSWER_SUBMIT = 'ANSWER_SUBMIT',
  COUNTDOWN_3 = 'COUNTDOWN_3',
  COUNTDOWN_2 = 'COUNTDOWN_2',
  COUNTDOWN_1 = 'COUNTDOWN_1',
  MATCH_START = 'MATCH_START',
  TIMER_WARNING = 'TIMER_WARNING',
  TIMER_CRITICAL = 'TIMER_CRITICAL',
  TIMEOUT = 'TIMEOUT',
  ANSWER_CORRECT = 'ANSWER_CORRECT',
  ANSWER_WRONG = 'ANSWER_WRONG',
  OPPONENT_CORRECT = 'OPPONENT_CORRECT',
  ROUND_WIN = 'ROUND_WIN',
  ROUND_LOSE = 'ROUND_LOSE',
  MATCH_FOUND = 'MATCH_FOUND',
  MATCH_WIN = 'MATCH_WIN',
  MATCH_LOSE = 'MATCH_LOSE',
  TROPHY_GAIN = 'TROPHY_GAIN',
  TROPHY_LOSS = 'TROPHY_LOSS',
  XP_GAIN = 'XP_GAIN',
  LEVEL_UP = 'LEVEL_UP',
  ARENA_UNLOCK = 'ARENA_UNLOCK',
  REWARD_OPEN = 'REWARD_OPEN',
  DIAMOND_GAIN = 'DIAMOND_GAIN',
  EMOTE_SEND = 'EMOTE_SEND',
  EMOTE_RECEIVE = 'EMOTE_RECEIVE',
  NOTIFICATION = 'NOTIFICATION',
  SPECIAL_PLAYER_RONALDO = 'SPECIAL_PLAYER_RONALDO',
}
