// OTOMATİK ÜRETİLDİ — docs/design/ui2/tools/gen_assets.py (kaynaklar: cuts.txt kesimleri + kullanıcı sanatı); elle düzenleme.
// Kaynak: kullanıcının referans mock'ları (docs/design/ui2/refs). Sayılar/fiyatlar sanatın DIŞINDA, canlı metindir.
export const UI2 = {
  ac_laurel: require('../../assets/ui2/ac-laurel.png'),
  ac_stadium: require('../../assets/ui2/ac-stadium.png'),
  arena_dunya: require('../../assets/ui2/arena-dunya.png'),
  arena_efsaneler: require('../../assets/ui2/arena-efsaneler.png'),
  arena_goat: require('../../assets/ui2/arena-goat.png'),
  arena_mahalle: require('../../assets/ui2/arena-mahalle.png'),
  arena_profesyonel: require('../../assets/ui2/arena-profesyonel.png'),
  arena_sampiyonlar: require('../../assets/ui2/arena-sampiyonlar.png'),
  banner_copass: require('../../assets/ui2/banner-copass.jpg'),
  banner_cosm: require('../../assets/ui2/banner-cosm.jpg'),
  banner_invite: require('../../assets/ui2/banner-invite.jpg'),
  banner_socialpack: require('../../assets/ui2/banner-socialpack.jpg'),
  frame_laurel: require('../../assets/ui2/frame-laurel.png'),
  gem_1400: require('../../assets/ui2/gem-1400.png'),
  gem_250: require('../../assets/ui2/gem-250.png'),
  gem_650: require('../../assets/ui2/gem-650.png'),
  gem_80: require('../../assets/ui2/gem-80.png'),
  home_modes_art: require('../../assets/ui2/home-modes-art.png'),
  hud_gem: require('../../assets/ui2/hud-gem.png'),
  md_bot: require('../../assets/ui2/md-bot.png'),
  mode_country_team: require('../../assets/ui2/mode-country-team.png'),
  mode_cozkazan: require('../../assets/ui2/mode-cozkazan.png'),
  mode_guess_who: require('../../assets/ui2/mode-guess-who.png'),
  mode_letter_team: require('../../assets/ui2/mode-letter-team.png'),
  mode_team_team: require('../../assets/ui2/mode-team-team.png'),
  mode_xox: require('../../assets/ui2/mode-xox.png'),
  nav_collection: require('../../assets/ui2/nav-collection.png'),
  nav_friends: require('../../assets/ui2/nav-friends.png'),
  nav_play: require('../../assets/ui2/nav-play.png'),
  nav_store: require('../../assets/ui2/nav-store.png'),
  nav_tournaments: require('../../assets/ui2/nav-tournaments.png'),
  pw_freeze: require('../../assets/ui2/pw-freeze.png'),
  pw_shield: require('../../assets/ui2/pw-shield.png'),
  pw_streak: require('../../assets/ui2/pw-streak.png'),
  pw_training: require('../../assets/ui2/pw-training.png'),
  pw_xp: require('../../assets/ui2/pw-xp.png'),
  qs_chest: require('../../assets/ui2/qs-chest.png'),
  rw_emote: require('../../assets/ui2/rw-emote.png'),
  rw_frame: require('../../assets/ui2/rw-frame.png'),
  rw_gems: require('../../assets/ui2/rw-gems.png'),
  sec_power: require('../../assets/ui2/sec-power.png'),
  sp_freeze2: require('../../assets/ui2/sp-freeze2.png'),
  sp_goal: require('../../assets/ui2/sp-goal.png'),
  sp_social: require('../../assets/ui2/sp-social.png'),
  sp_speed: require('../../assets/ui2/sp-speed.png'),
  tn_banner_art: require('../../assets/ui2/tn-banner-art.png'),
  tn_bigreward: require('../../assets/ui2/tn-bigreward.png'),
  up_handshake: require('../../assets/ui2/up-handshake.png'),
} as const;
export type Ui2AssetKey = keyof typeof UI2;
